### ISSUE TITLE
Taxonomies Being Ignored on Search

### ISSUE THREAD

**Issue by jungerpants** [kylephillips/simple-locator#101]
Hey Kyle - long time user, first time caller.

I'm seeing taxonomies being ignored on the default shortcode; the distance mapping is working OK but rather than showing only posts in the selected category, it's showing everything.

Anyone else experiencing this?

**Comment by jakob-metro** [comment]
Found this issue looking for a solution, having this problem as well. It looks like the taxonomy fields never get sent to the ajax post, there might be some funky stuff going on in the frontend where the ajax request data gets built.

**Comment by digitaldotink** [comment]
woot woot, thanks @kylephillips!
