### ISSUE TITLE
Javascript error prevents user from saving from Draft to Published

### ISSUE THREAD

**Issue by lmartins** [kylephillips/simple-locator#67]
I have an entry that just wont allow me to to published, keeping the post as draft.
I've noticed is trying to run a modal with a error message as shown here:
https://www.dropbox.com/s/bx7kpic887yrre4/Screenshot%202015-10-14%2020.04.27.png?dl=0

Anything I can do about this?

**Comment by kfrancis** [comment]
Any news here?
