### ISSUE TITLE
Incorrect Form Field error

### ISSUE THREAD

**Issue by chappydboz** [kylephillips/simple-locator#75]
i'm getting an intermittent form error printed to the screen when the page first loads.. it says 'Incorrect Form Field' in the red form error section. My site is on https and attempting to load initial results based on user's location.  

looking thru the plugin code, it seems that the error might be stemming from a failed NONCE check. 

![screen shot 2016-11-02 at 7 54 42 pm](https://cloud.githubusercontent.com/assets/867659/19952836/3886aacc-a136-11e6-8a1d-b104e961c9ec.png)

view the page in question here: 
https://bloodyrevolution.com/where-to-find/

**Comment by STRAND-C** [comment]
Did you find a fix for this? I am getting the same error with https too.

**Comment by ahamill85** [comment]
I am also having this same issue. It seems to only happen to me only after reloading after selecting "allow" when asked if I want to share my location. If I clear that setting and reload the page, it'll ask me again and it'll work fine. Also, if I click the "use my location" button on the form, it'll work.

**Comment by GoodPixe1** [comment]
I'm getting this issue when 'Show Default Map on Page Load' is checked. It's important that my map is always visible with each location pinned on it, but instead of the map I just get 'Incorrect Form Field'. Did you guys come up with a solution?

**Comment by STRAND-C** [comment]
Nope. Would love a fix for this if anyone knows of one :)

**Comment by visual23** [comment]
I had the same problem and it was only happening on mobile devices. I narrowed down to the nonce value not being available when the "sendFormData" function was called. What I did to resolve this was I triggered geo button after the "generate_nonce" functions success. Basically delaying the "sendFormData" function until the nonce value was available. I did all of this in assets/js/simple-locator.js. I'm sure it's quite a hack but it's working. Enjoy!

**Comment by STRAND-C** [comment]
@visual23 would you mind sharing this code?

**Comment by TerrenceLP** [comment]
Has anyone seen this get fixed in a future master update?

**Comment by visual23** [comment]
@ahamill85 thanks for doing that. I had made some changes to the plugin so the results would show up on another page. My hack wouldn't work for everyone.

**Comment by visual23** [comment]
@STRAND-C ahamill85's fix should work for you

**Comment by STRAND-C** [comment]
@ahamill85 thanks very much for this you've saved me here 👍. Thanks to @visual23 too - I understand where you're coming from!

**Comment by kylephillips** [comment]
V2 removes all calls to admin-ajax, replacing all requests with custom API endpoints. For this reason, the nonce will be removed (all data is publicly queryable). This should no longer be an issue after release.
