### ISSUE TITLE
Issue with callbacks

### ISSUE THREAD

**Issue by Deester4x4jr** [kylephillips/simple-locator#79]
I am trying to format the infoWindow of my markers, and I am falling flat on my face.  I am using this:

```
function simple_locator_infowindow_flo($infowindow, $result,$count) {

  return '<div class="start-here">'.$infowindow.'</div>';
} add_filter('simple_locator_infowindow','simple_locator_infowindow_flo');
```

And that seems to work ok.  However, there is very limited information there.  I tried to get something out of `$result` and `$count` but they seem to be empty.  Any idea what I'm doing wrong?

My end goal is to have the infowindow just have the title, and a link that says "Get Directions" and links to google maps with a pre-populated "To Address" field.  But until I can find the data I am looking for, I can't get very far.

Any help is appreciated.

Thanks!

-Josh-

**Comment by Deester4x4jr** [comment]
Also, I tried sending each variable to DebugBar to debug, but nothing happens...

**Comment by Deester4x4jr** [comment]
Just FYI, I created a bit of a workaround, by defining my own javascript function that collects the address and business name from the element clicked in the list and then matching it with the id of the marker which I was able to get by parsing the `$infowindow` parameter that I am able to get data out of in `simple_locator_infowindow`.  Its hacky, but it works... so no rush.  I would like to know what I am doing wrong in the first place though.

Thanks,

-Josh-

**Comment by MikeiLL** [comment]
I'd love to see further input on this myself.

**Comment by spingary** [comment]
Here's how I used the filter and it works great:

```
add_filter('simple_locator_infowindow','my_locator_infowindow',10,2);
function my_locator_infowindow($infowindow, $result,$cnt) {
    $infowindow = sprintf('<div class="infowindow"><h5>%s</h5><p>%s</p><p class="listing_rates">%s</p><p class="btn-details"><a href="%s">Details &gt;</a></p></div>',
        $result->title, $result->friendly_address,$result->listing_page_rates, get_permalink($result->id));
    return $infowindow;
    /*
    For reference, here's an example of what's in my $result var (I have some custom fields)
    [title] => 3rd Ward Car Park
    [id] => 268
    [friendly_address] => N Broadway and St. Paul
    [listing_page_rates] => 
    [latitude] => 43.034636
    [longitude] => -87.90693499999998
    [distance] => 0.7335322053458226
    */
}
```

Hope this helps.
Gary
