### ISSUE TITLE
[New Feature] Allow locations of the same name to be created when the address differs

### ISSUE THREAD

**Issue by wturnerharris** [kylephillips/simple-locator#81]
**Issue:** 
Bulk importing a CSV list of locations fails to add locations of the same name; that is, adding places of the same name with varying addresses fails on import because the title is the same. 

**Ideal Behavior:**
Adding a more robust post-lookup to compare a unique field like the geocodes or street address would be more reliable in the case of the same name and different place.

**Comment by kylephillips** [comment]
Addressed/fixed in v2.0.2 with unique identifier flag.
