### ISSUE TITLE
Search results open on new page.

### ISSUE THREAD

**Issue by GoodPixe1** [kylephillips/simple-locator#82]
Hello, is it possible to have a search form on one page and display results on a different page? e.g. I have a search form on the home page that takes the user to a 'find a location' page with search results.

Thanks!

**Comment by Jakob-Maudience** [comment]
I wasn't able to find a good way of doing this, so until I find out how to do this properly in php, I'm just doing it with js. I don't recommend this method in the long run, it's quite janky.

`$(window).load(function () { // This function needs to take place after the map is initialized.

	if (isOnSearchPage) { // Some condition to check if we are on the search page.
		var search = getParameterByName('search');
		if (search !== null) { // If we have a valid get parameter.
			$('.address-input input').val(search); // Set the value of the input
			$('.wpslsubmit').click(); // Simulate a form submition
		}
	}
});

function getParameterByName(name, url) {
    if (!url) url = window.location.href;
    name = name.replace(/[\[\]]/g, '\\$&');
    var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, ' '));
} // Credit: https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript#answer-901144`

**Comment by kylephillips** [comment]
This will be possible in V2 once it's released by adding a "resultspage" parameter to the shortcode. Example: [simple_locator ajax="false" resultspage="123"]. In that case, the form would redirect to the page with an ID of 123, and the results would be placed within the content area. There will also be a "simple_locator_results" action available to display results elsewhere within the page template.
