### ISSUE TITLE
Custom taxonomies with hyphen returns zero results

### ISSUE THREAD

**Issue by husani** [kylephillips/simple-locator#85]
I have a custom taxonomy on a custom post type. Adding that taxonomy to the search form via shortcode breaks the search -- there are no results if a taxonomy item is selected, even though there should be results.

Turns out my custom taxonomy has a hyphen, which breaks the SQL.

A fix for this can be applied in LocationSearch.php, line 190 -- add a grave around each instance of the $taxonomy_name variable.

**Comment by christooma** [comment]
Nice. Have you experienced any issues displaying taxonomies in the list of search results?  I see a custom taxonomy options in the drop down under “results display” but it doesn’t ever populate with the taxonomy terms
