### ISSUE TITLE
Cannot delete content from "street address line 2" field

### ISSUE THREAD

**Issue by FriendlyWP** [kylephillips/simple-locator#92]
A previously saved or published location with anything in the Street Address Line 2 field restores that content to the field on Save/Update, even if the content in that field was deleted. The field's content can be edited (replace the content with a space works, for instance) but it cannot be blank once content has been entered & saved. 

A space in the field creates an unwanted line break on the display-side, so that's not an ideal solution. :) Thanks for your help!

**Comment by kylephillips** [comment]
This was fixed in [this commit](https://github.com/kylephillips/simple-locator/commit/238951c13e66d282e06b8f0be19975e098cac9b6#diff-59d4d3f269402901fb4eb3e9a6feda26), which will be part of the next release.
