### ISSUE TITLE
admin ajax 500 error load-scripts.php

### ISSUE THREAD

**Issue by TransformReality** [kylephillips/simple-locator#95]
Running newest git version of Simple Locator and i keep getting this import error, independent of the version im using. So do i need to change my wordpress configuration to fix this issue?

`jquery.js?ver=1.12.4-wp:formatted:4206 POST https://example.com/wp-admin/admin-ajax.php 500
send @ jquery.js?ver=1.12.4-wp:formatted:4206
ajax @ jquery.js?ver=1.12.4-wp:formatted:3990
o.doImport @ simple-locator-admin.min.js:1
o.startImport @ simple-locator-admin.min.js:1
(anonymous) @ simple-locator-admin.min.js:1
dispatch @ jquery.js?ver=1.12.4-wp:formatted:2105
r.handle @ jquery.js?ver=1.12.4-wp:formatted:1985`

ERROR LOG:
`Stack trace:
#0 /home/covdqshe/public_html/wp-content/plugins/simple-locator/app/Services/Import/Listeners/Import.php(28): SimpleLocator\Services\Import\Listeners\Import->doImport()
#1 /home/covdqshe/public_html/wp-content/plugins/simple-locator/app/Services/Import/Events/RegisterImportEvents.php(76): SimpleLocator\Services\Import\Listeners\Import->__construct()
#2 /home/covdqshe/public_html/wp-includes/class-wp-hook.php(287): SimpleLocator\Services\Import\Events\RegisterImportEvents->ImportRequestMade('')
#3 /home/covdqshe/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /home/covdqshe/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /home/covdqshe/public_html/wp-admin/admin-ajax.php(175): do_action('wp_ajax_wpsldoi...')
#6 {main}
  thrown in /home/covdqshe/public_html/wp-content/plugins/simple-locator/app/Services/Import/Listeners/Import.php on line 57`

---
WP Version 5.3.2
Php Version: 7.2
Simple Location Version: 2.0.1

Please advise if you can.

**Comment by kylephillips** [comment]
Closing this, as it should be sorted out in v2
